name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'GitHub actions env workaround'
        run: 'echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV'

      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.4.5'
          enable-stack: true
          stack-version: 'latest'

      - name: Install Dependencies
        run: |
          stack --no-terminal --install-ghc install --bench --only-dependencies

      - name: Build
        id: build
        run: |
          stack --no-terminal build --bench --test --no-run-tests --haddock --no-run-benchmarks --no-haddock-deps

      - name: Test
        id: test
        run: |
          stack --no-terminal test
      - name: Build Docs
        run: |
          FILEPATH=$(stack haddock --no-haddock-deps 2>&1 | tail -5 | head -n 1)
          echo $FILEPATH
          FOLDERPATH=$(dirname $FILEPATH)
          echo $FOLDERPATH
          cp -a $FOLDERPATH ./html
          echo "truelayer.bank.rly.rocks" > ./html/CNAME
      - name: Publish Docs
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          enable_jekyll: true
